subscriptions:
  ibmassetrepo:
    name: ibm-assetrepo
    subscription:
      channel: v1.4
      installPlanApproval: Automatic
      name: ibm-integration-asset-repository
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace